name: Weekly Explainer Automation

on:
  schedule:
    # Run every Monday at 8:00 AM
    - cron: '0 8 * * 1'
  workflow_dispatch:
    # Allow manual triggering with options
    inputs:
      priority:
        description: 'Number of new explainers to create'
        required: true
        default: '5'
      update_all:
        description: 'Update all existing explainers with new information'
        required: true
        default: 'true'
        type: boolean

jobs:
  explainer-automation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
          
      - name: Generate explainer update report
        run: |
          python knowledge-base/Code_Suggest/weekly-explainer-update.py --days=7 --output=explainer-update-report.md
          
      - name: Create/update explainer articles
        run: |
          python knowledge-base/Code_Suggest/auto-explainer-creator.py --report=explainer-update-report.md --priority=${{ github.event.inputs.priority || 5 }} ${{ github.event.inputs.update_all == true && '--update-all' || '' }}
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add explainers/*.md explainer-updates-log.md
          git commit -m "Weekly explainer update $(date +'%Y-%m-%d')" || echo "No changes to commit"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Create issue with update report
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Weekly Explainer Update Report
          content-filepath: ./explainer-update-report.md
          labels: documentation, explainer